<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>total payment</name>
   <tag></tag>
   <elementGuidId>3706c1ab-6e70-40aa-bf82-ddecab3f31ca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;header&quot;)/div[@class=&quot;order-header&quot;]/div[@class=&quot;order-box&quot;]/div[@class=&quot;order-summary-section&quot;]/div[@class=&quot;order-container&quot;]/div[@class=&quot;header-amount&quot;][count(. | //div[@class = 'header-amount' and (text() = 'Rp1.240.000' or . = 'Rp1.240.000')]) = count(//div[@class = 'header-amount' and (text() = 'Rp1.240.000' or . = 'Rp1.240.000')])]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.header-amount</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//nav[@id='header']/div[2]/div/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Rp1.240.000&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>816865a7-e690-4dde-96ec-01591e29baa4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>header-amount</value>
      <webElementGuid>95f4fa03-22f0-4c93-b160-099e91cccbd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Rp1.240.000</value>
      <webElementGuid>da0a5dde-c99e-4d3a-8c15-5554b07a10eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header&quot;)/div[@class=&quot;order-header&quot;]/div[@class=&quot;order-box&quot;]/div[@class=&quot;order-summary-section&quot;]/div[@class=&quot;order-container&quot;]/div[@class=&quot;header-amount&quot;]</value>
      <webElementGuid>ea5a945f-1b91-479a-8900-620c4b7b664a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//nav[@id='header']/div[2]/div/div/div/div</value>
      <webElementGuid>59789f9f-8f18-4b73-84ff-245090bee5fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rincian'])[1]/preceding::div[3]</value>
      <webElementGuid>146d2adb-d63f-4c43-88f2-e6b884555069</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Rp1.240.000']/parent::*</value>
      <webElementGuid>986f4ce3-def6-4d1c-9126-0133126d11be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div</value>
      <webElementGuid>23d24e39-0ffa-4bbe-8cf1-89b1ab8636a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Rp1.240.000' or . = 'Rp1.240.000')]</value>
      <webElementGuid>0575b904-c684-47b8-a0a3-60f644f3222a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
