<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_College</name>
   <tag></tag>
   <elementGuidId>387aa4b0-1f52-4bce-937c-2a731bd3b634</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ab500164171b-0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ab500164171b-0']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'ab500164171b-0' and (text() = 'College' or . = 'College')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=option[name=&quot;College&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>411a60cf-320a-4b5b-ba55-9e686ff44a27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-option ng-option-marked</value>
      <webElementGuid>db666ad1-d108-4e5d-b793-310868c6029c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>346f116a-273f-479c-aa33-08360e7cf2f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>be673884-6aac-4738-9e22-7b9cf15528fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ab500164171b-0</value>
      <webElementGuid>1b4f6fb5-3dc6-4861-ba81-32b18db9fa8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>College</value>
      <webElementGuid>14ca0e2e-c46b-4975-89d2-84b5a1729957</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ab500164171b-0&quot;)</value>
      <webElementGuid>a869e00a-926c-4eb0-9c77-f8d542fc0ed6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='ab500164171b-0']</value>
      <webElementGuid>ebd738e8-08bf-4aff-9c54-2b3537994351</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ng-dropdown-panel[@id='ab500164171b']/div/div[2]/div</value>
      <webElementGuid>6d9f0a6c-053b-4063-b54c-c8cf397c2e6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Log Out'])[2]/following::div[4]</value>
      <webElementGuid>959e6b7c-c18c-47dd-894a-8e571af94188</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='College Graduates'])[1]/preceding::div[1]</value>
      <webElementGuid>9c448313-184d-4d2c-8c99-52021a1542d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ng-dropdown-panel/div/div[2]/div</value>
      <webElementGuid>5910d21c-def7-4f46-a034-deacd0584160</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'ab500164171b-0' and (text() = 'College' or . = 'College')]</value>
      <webElementGuid>47267100-73ea-43bb-99f9-b796c14fa319</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
