<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input birthplace</name>
   <tag></tag>
   <elementGuidId>8891a35f-f1f3-4955-8336-639ff3115e28</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#birthplace</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='birthplace']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Place Of Birth&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e4668b66-e145-4b10-bd24-e0bd8130365b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>birthplace</value>
      <webElementGuid>5df329a2-9b9a-4a76-bb79-b4a67d23a959</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2f50d27e-bdc1-4e90-bd15-fb43c4cb1709</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Place Of Birth</value>
      <webElementGuid>d7ae6b87-c638-4035-9a03-5c47b8cb5fba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>birthplace</value>
      <webElementGuid>885f98e9-353f-4330-b132-e73816db1124</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>birthplace</value>
      <webElementGuid>3d5b82f1-69af-47cb-a459-660ee0189f5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ec-form-control-rounded ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>c8b04285-e98c-416b-ae65-6c34c9116bc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;birthplace&quot;)</value>
      <webElementGuid>e332da4e-7fc4-451b-9fde-f42a879709e8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='birthplace']</value>
      <webElementGuid>a4b18477-86ec-4021-999a-0bf33a230fe4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/input</value>
      <webElementGuid>40caf8ed-a4e8-4752-97a7-14792d2fa33e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'birthplace' and @type = 'text' and @placeholder = 'Place Of Birth']</value>
      <webElementGuid>e6d7aedb-6900-42aa-ae04-619bef134487</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
